name = "cfworker-scratchcard"
main = "src/index.ts"
compatibility_date = "2022-06-16"

[[r2_buckets]]
binding = 'SCRATCHCARD_BUCKET'
bucket_name = 'scratchcard'
preview_bucket_name = 'scratchcard'

[[kv_namespaces]]
binding = "SCRATCHCARD_KV"
id = "2fa0886c0bd648c09a2aadde66eea0fe"
preview_id = "bfe2f5b12ae4439aa182af6ae385d09e"

[site]
bucket = "./spa/build"